/*insert new structured item 360(2022) into old format*/

insert into wm_catalog2( item_num,
    gtin ,
    item_status ,
    item_description ,
    merchant ,
    merchant_email ,
    supplier_stock_id ,
    department ,
    fineline ,
    supplier_id ,
    contract_seq_num ,
    supplier_name ,
    buying_region ,
    replenishable ,
    corporate_orderbook ,
    last_changed_date ,
    orderable_pack_qty ,
    warehouse_pack_qty ,
    unit_cost ,
    retail_price ,
    store_item_type ,
    store_item_subtype ,
    "1p_offer_lifecycle_status" ,
    wpid ,
    item_id ,
    upc ,
    wm_shelf_name ,
    site_start_date ,
    site_end_date ,
    wm_page_url ,
    buy_box_status 
     )
 select item_num,
    gtin ,
    item_status ,
    item_description ,
    merchant ,
    merchant_email ,
    supplier_stock_id ,
    department ,
    fineline ,
    supplier_id ,
    contract_seq_num ,
    supplier_name ,
    buying_region ,
    replenishable ,
    corporate_orderbook ,
    last_changed_date ,
    orderable_pack_qty ,
    warehouse_pack_qty ,
    unit_cost ,
    retail_price ,
    store_item_type ,
    store_item_subtype ,
    "1p_offer_lifecycle_status" ,
    wpid ,
    item_id ,
    upc ,
    wm_shelf_name ,
    site_start_date ,
    site_end_date ,
    wm_url ,
    buy_box_status 
     
    from wm_catalog_2022;